app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v1.0.2"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.31.165"
  port: 3307
  username: "root"
  password: "root123"
  database: "gotest"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.31.165"
  port: 6381
  password: ""
  db: 0
  pool_size: 100